//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEP_API_CRUD_EXAMPLE.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string city { get; set; }
        public string branch { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
