//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace WEP_API_CRUD_EXAMPLE.Models
{
    [Serializable]
    internal class UnintentionalCodeFirstException : Exception
    {
        public UnintentionalCodeFirstException()
        {
        }

        public UnintentionalCodeFirstException(string message) : base(message)
        {
        }

        public UnintentionalCodeFirstException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected UnintentionalCodeFirstException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}